Feature selection standard morphs
hpi-swa-teaching/MorphicAPIExplorer pull request #27
Opened 2021-06-06 14:58 UTC by kathrinthenhausen

2021-06-06 16:53 UTC, Zyranix reviewed
Warum defaultMorphs nicht auf Klassenseite?

2021-06-06 16:55 UTC, Zyranix requested changes
Nach super und lokalen Variablen immer eine Leerzeile!

2021-06-06 19:06 UTC, taminob reviewed
Wie bereits erwähnt, sollten keine Punkte am Ende einer Methode sein und auch nicht am Ende eines Code-Blocks (also [self method] statt [self method.]). Nach lokalen Variablen folgt allerdings nach Coding Standards meines Wissens keine leere Zeile (nach super aber schon).

2021-06-06 19:25 UTC, Zyranix commented
Kann es sein, dass der Punkt mit den lokalen Variablen sogar im Coding Standard fehlt?

2021-06-06 20:10 UTC, taminob commented
Also im Code gibt es zahlreiche Stellen, an denen es keine Leerzeile nach lokalen Variablen gibt und ich kann mich gerade an keine Methode erinnern, in der es eine gab. In den Coding Standards steht diesbezüglich nichts und wäre definitiv noch etwas, was wir in die Coding Standards aufnehmen sollten

2021-06-07 08:37 UTC, kathrinthenhausen commented
> Warum defaultMorphs nicht auf Klassenseite?

stammt nicht von diesem Issue

2021-06-07 08:56 UTC, taminob approved these changes

2021-06-07 09:51 UTC, postmartem approved these changes

2021-06-07 12:01 UTC, merged