Implemented a button test
hpi-swa-teaching/MorphicAPIExplorer pull request #48
Opened 2021-06-18 12:52 UTC by taminob

2021-06-18 14:35 UTC, Zyranix commented on packages/MorphicAPIExplorer-Tests.package/MEXOverViewTestsWithFullCategories.class/instance/setUp.st
> +	1 to: defaultCollectionSize do: [:anIndex | full add: (MEXCategory newNamed: 'a' havingImage: MEXScalableImageMorph new havingDefaultMorph: Morph new withMethodList: {MEXMethod newWithName: 'b'})].
Very long line

2021-06-18 14:36 UTC, Zyranix commented on packages/MorphicAPIExplorer-Tests.package/MEXOverViewTestsWithFullCategories.class/instance/testCategoryButtonToExplorationView.st
> +	((view submorphs select: [:each | each isKindOf: MEXPluggableButtonMorph]) select: [:each | each label isKindOf: MEXScalableImageMorph]) first performAction.
dont use each, but a|anWORD (-> coding standard)

2021-06-18 14:41 UTC, Zyranix requested changes
test looks good, only small refactoring stuff should be fixed

2021-06-18 14:41 UTC, Zyranix commented on packages/MorphicAPIExplorer-Tests.package/MEXTestCaseForUI.class/instance/getOpenWindowsWithModel..st
> +	^ ActiveWorld submorphs  select: [:each|( each isKindOf: PluggableSystemWindow) and: (each model isKindOf: aClass)]
dont use each, but a|anWORD (-> coding standard)

2021-06-18 14:41 UTC, Zyranix commented on packages/MorphicAPIExplorer-Tests.package/MEXOverViewTestsWithFullCategories.class/instance/testCategoryButtonToExplorationView.st
> +	((view submorphs select: [:each | each isKindOf: MEXPluggableButtonMorph]) select: [:each | each label isKindOf: MEXScalableImageMorph]) first performAction.
don't use each

2021-06-18 14:41 UTC, Zyranix commented on packages/MorphicAPIExplorer-Tests.package/MEXOverViewTestsWithFullCategories.class/instance/setUp.st
> +	1 to: defaultCollectionSize do: [:anIndex | full add: (MEXCategory newNamed: 'a' havingImage: MEXScalableImageMorph new havingDefaultMorph: Morph new withMethodList: {MEXMethod newWithName: 'b'})].
very long line

2021-06-18 14:42 UTC, Zyranix commented on packages/MorphicAPIExplorer-Tests.package/MEXOverViewTestsWithFullCategories.class/instance/setUp.st
>  	full  := OrderedCollection new.
test

2021-06-20 11:18 UTC, Zyranix approved these changes
Looks fine now

2021-06-20 16:36 UTC, sinahenning reviewed
Top!

2021-06-20 16:42 UTC, sinahenning approved these changes

2021-06-21 10:06 UTC, merged