Feature overview search improvement
hpi-swa-teaching/MorphicAPIExplorer pull request #73
Opened 2021-07-14 16:27 UTC by taminob

closes #72

2021-07-15 16:17 UTC, postmartem commented on packages/MorphicAPIExplorer-Core.package/MEXToolOverView.class/instance/findSearchListInDependents.st
> +	^ (self dependents select: [:aDependent | aDependent isKindOf: PluggableTreeMorph]) first
Hier verwendet ihr isKindOf, wenn ihr meint es geht nicht ohne viel Aufwand schöner und ihr habt darüber schon nachgedacht ist es wohl so

2021-07-15 16:19 UTC, postmartem commented on packages/MorphicAPIExplorer-Core.package/MEXToolOverView.class/instance/updateSearchList..st
> +			self findSearchListInDependents removeFilter.
Hier kann mindestens auf das self eine Kaskade angewandt werden

2021-07-15 16:26 UTC, postmartem commented on packages/MorphicAPIExplorer-Tests.package/MEXOverViewTestsWithFullCategories.class/instance/testSearchBarUpdatesSearchList.st
> +	self assert: (searchList filteredItems reject: [:anItem | searchList roots includes: anItem]) notEmpty.
Hier vielleicht überprüfen, ob es auch genau eins statt nur irgendwelche gefundenen Elemente gibt

2021-07-15 16:27 UTC, postmartem requested changes
Eventuell noch einen Test hinzufügen, ob die Searchbar nach Eingabe eines Buchstabens visible ist, weil ja das gegenteil auch getestet wird

2021-07-16 14:32 UTC, taminob commented on packages/MorphicAPIExplorer-Core.package/MEXToolOverView.class/instance/findSearchListInDependents.st
> +	^ (self dependents select: [:aDependent | aDependent isKindOf: PluggableTreeMorph]) first
Wir kennen zumindest keinen besseren Weg, einzige andere Möglichkeit wäre wohl, noch eine Instanzvariable dafür hinzuzufügen, wobei das Befüllen der Instanzvariable auch ein Problem darstellt.

2021-07-16 14:37 UTC, sinahenning commented on packages/MorphicAPIExplorer-Core.package/MEXToolOverView.class/instance/updateSearchList..st
> +			self findSearchListInDependents removeFilter.
jetzt kaskadiert

2021-07-16 14:38 UTC, taminob commented on packages/MorphicAPIExplorer-Tests.package/MEXOverViewTestsWithFullCategories.class/instance/testSearchBarUpdatesSearchList.st
> +	self assert: (searchList filteredItems reject: [:anItem | searchList roots includes: anItem]) notEmpty.
Es gibt aber mehr Treffer, um genau zu sein sind alle Kategorien ('a') sowie die darin liegenden Methoden 'b' ausgewählt, wobei es 20 Mal 'a' und 'b' gibt und die 40 zu hardcoden wäre wohl noch problematischer

2021-07-16 15:11 UTC, merged